### ISSUE TITLE
crashes when the chocolate milk bucket removes a debuff effect

### ISSUE THREAD

**Issue by SimoneComitini** [Shnupbups/Sweet-Tooth#1]
"Title", here is the crash report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 9/2/19 5:07 PM
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.shnupbups.sweettooth.items.ChocolateMilkBucketItem.method_7861(ChocolateMilkBucketItem.java:39)
	at net.minecraft.class_1799.method_7910(class_1799.java:205)
	at net.minecraft.class_1309.method_6040(class_1309.java:2643)
	at net.minecraft.class_3222.method_6040(class_3222.java:1071)
	at net.minecraft.class_1309.method_6076(class_1309.java:2537)
	at net.minecraft.class_1309.method_5773(class_1309.java:2047)
	at net.minecraft.class_1657.method_5773(class_1657.java:277)
	at net.minecraft.class_3222.method_14226(class_3222.java:388)
	at net.minecraft.class_3244.method_18784(class_3244.java:196)
	at net.minecraft.class_2535.method_10754(class_2535.java:234)
	at net.minecraft.class_3242.method_14357(class_3242.java:171)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774)
	at net.minecraft.class_1132.method_3748(class_1132.java:161)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.shnupbups.sweettooth.items.ChocolateMilkBucketItem.method_7861(ChocolateMilkBucketItem.java:39)
	at net.minecraft.class_1799.method_7910(class_1799.java:205)
	at net.minecraft.class_1309.method_6040(class_1309.java:2643)
	at net.minecraft.class_3222.method_6040(class_3222.java:1071)
	at net.minecraft.class_1309.method_6076(class_1309.java:2537)
	at net.minecraft.class_1309.method_5773(class_1309.java:2047)
	at net.minecraft.class_1657.method_5773(class_1657.java:277)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 226
	Entity Name: simoncraft980
	Entity's Exact location: -258.95, 4.00, -60.45
	Entity's Block location: World: (-259,4,-61), Chunk: (at 13,0,3 in -17,-4; contains blocks -272,0,-64 to -257,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:388)
	at net.minecraft.class_3244.method_18784(class_3244.java:196)
	at net.minecraft.class_2535.method_10754(class_2535.java:234)

-- Ticking connection --
Details:
	Connection: net.minecraft.class_2535@625c905f
Stacktrace:
	at net.minecraft.class_3242.method_14357(class_3242.java:171)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774)
	at net.minecraft.class_1132.method_3748(class_1132.java:161)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4616365600 bytes (4402 MB) / 6053429248 bytes (5773 MB) up to 6053429248 bytes (5773 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx6144m
	Fabric Mods: 
		adorn: Adorn 1.2.1+1.14.4
		appleskin: AppleSkin 1.0.6
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		bambootweaks: Bamboo Tweaks 1.14.4-0.1.5
		cloth: Cloth Events 0.4.0
		cloth-config: Cloth Config 0.2.4+build.17
		cloth-config2: Cloth Config v2 1.0.0
		coloredinnerwool: Colored Inner Wool 0.2.0
		crafty: Crafty 0.3.3+1.14.1
		fabric: Fabric API 0.3.2+build.218-1.14
		fabric-api-base: fabric-api-base 0.1.0+5914746355
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.40+build.1
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.13+68fade5542
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.3+b02deb0042
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.6.1+build.164
		fiber2cloth: Fiber To Cloth 1.0.1
		jankson: Jankson 1.0.0+j1.1.2
		libgui: LibGui 1.2.5
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.7.9+build.118
		nbtcrafting: NBT Crafting 1.2.4+1.14.4
		nbttooltip: NBT Tooltip 1.14-1.0.3
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.5.1
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.40
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.2
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		pushable: Pushable Block Entities 1.0.0
		roughlyenoughitems: Roughly Enough Items 3.0-pre+build.1
		sweettooth: Sweet Tooth 1.0.0
		towelette: Towelette 1.10.1
	Player Count: 1 / 8; [class_3222['simoncraft980'/226, l='TestWorld', x=-258.95, y=4.00, z=-60.45]]
	Data Packs: vanilla, file/armor_stand_book.zip, file/Realistic recipes (incompatible), file/rider_quest.zip (incompatible), file/mci (incompatible), file/FH stonecutter damage v1.0.0 (incompatible), fabric/fabric-mining-levels-v0, fabric/adorn, fabric/towelette, file/Colorful Cauldron datapack v1.0.0.zip (incompatible), file/VanillaTweaks_c755177.zip (incompatible), file/coordinates hud v1.1.0.zip (incompatible), file/sethome v1.2.0.zip (incompatible), file/Custom Spawns Data Pack (incompatible), fabric/bambootweaks, fabric/pushable, fabric/sweettooth
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by Shnupbups** [comment]
Oh bollocks, I thought I fixed this. Will look into it!

**Comment by Shnupbups** [comment]
Should be fixed in 1.0.1
